apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cooking-clipper-operator
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "list", "watch", "get", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch", "get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
